name: Release
on:
  release:
    types: [created]
jobs:
  publish:
    name: Hex Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.5
        with:
          otp-version: 23.2
          elixir-version: 1.11.0
      - name: Build
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Publish
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: |
          mix hex.publish --yes
